### ISSUE TITLE
jOOQ returning one value but streaming a collection

### ISSUE THREAD

**Issue by ilopmar** [micronaut-graal-tests/micronaut-jooq-graal#3]
@morki can you please explain why here:

https://github.com/micronaut-graal-tests/micronaut-jooq-graal/blob/120abd03b8a980c7780d1035ac6d10e2d7800363/src/main/java/example/jooq/repositories/OwnerRepository.java#L34-L42

it's necessary to stream the result and try to find just one? Is this because there is no difference in jOOQ API for returning only one row vs returning more?

Thanks!

**Comment by morki** [comment]
@ilopmar I will fix this and some other things. For example, now the ResultSet is leaking and not closed. We use kotlin a have many kotlin extension functions for this type of tasks, so I did it wrong here. Now I use the real code from us and make it better.
PR will come.

**Comment by ilopmar** [comment]
Awesome!

**Comment by morki** [comment]
@ilopmar can we close this now?

**Comment by ilopmar** [comment]
Yes.
